DATA  SEGMENT
BUFF1 DB 4FH,0B6H,7CH,34H,56H,1FH
BUFF2 DB 13H,24H,57H,68H,0FDH,9AH
SUM   DB 6 DUP(0)
CONT DB 3
DATA ENDS
;
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
START: MOV AX,DATA
       MOV DS,AX
       MOV SI,OFFSET BUFF1
       MOV DI,OFFSET BUFF2
       MOV BX,OFFSET SUM
       MOV CL,CONT
       MOV CH,0
       CLC
GOON:  MOV AX,[SI]
       ADC AX,[DI]
       ADD SI,2
       ADD DI,2
       MOV [BX],AX
       ADD BX,2
       LOOP GOON
       MOV AH,4CH
       INT 21H
       CODE ENDS
END START
